image:
  name: pulumi/pulumi-python:latest
  entrypoint: [""]

stages:
  - validate
  - install
  - preview
  - dev

cache:
  paths:
    - .pulumi
    - __pycache__/
    - .venv/

variables:
  AWS_REGION: "us-east-2"
  PULUMI_BACKEND_URL: "s3://${PULUMI_S3_BUCKET}"

before_script:
  - echo "Setting up environment variables"
  - export AWS_REGION=$AWS_REGION
  - export PULUMI_CONFIG_PASSPHRASE=$PULUMI_CONFIG_PASSPHRASE
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export PULUMI_BACKEND_URL=$PULUMI_BACKEND_URL
  - pulumi login ${PULUMI_BACKEND_URL}

validate:
  stage: validate
  script:
    - echo "Validating project structure"
    - |
      if [ ! -f "requirements.txt" ]; then
        echo "ERROR: requirements.txt not found!"
        echo "Please create requirements.txt with Pulumi dependencies"
        exit 1
      fi
    - |
      if [ ! -f "Pulumi.yaml" ]; then
        echo "ERROR: Pulumi.yaml not found!"
        echo "Please run 'pulumi new' to initialize your project"
        exit 1
      fi
    - |
      if [ ! -f "__main__.py" ]; then
        echo "ERROR: __main__.py not found!"
        echo "Please create your main Pulumi program file"
        exit 1
      fi
    - echo "Project structure validation passed"
  only:
    - branches

install:
  stage: install
  script:
    - echo "Setting up Python virtual environment"
    - python3 -m venv .venv
    - source .venv/bin/activate
    - echo "Upgrading pip"
    - pip install --upgrade pip
    - echo "Installing Python dependencies"
    - pip install -r requirements.txt
    - echo "Verifying Pulumi installation"
    - python -c "import pulumi; print('Pulumi version:', pulumi._version)"
    - echo "Dependencies installed successfully"
  artifacts:
    paths:
      - .pulumi
      - __pycache__/
      - .venv/
    expire_in: 1h
  only:
    - branches
  when: always
  dependencies:
    - validate

preview:
  stage: preview
  script:
    - echo "Activating virtual environment"
    - source .venv/bin/activate
    - echo "Running Pulumi preview"
    - pulumi stack select dev || pulumi stack init dev
    - pulumi preview --stack dev --diff --non-interactive --color always
  dependencies:
    - install
  only:
    - branches
  # Changed from 'manual' to 'on_success' to run automatically
  when: on_success
  needs:
    - install

deploy-to-dev:
  stage: dev
  script:
    - echo "Running Pulumi up"
    - pulumi stack select dev || pulumi stack init dev
    - pulumi up --yes --non-interactive --color always --no-preview
  only:
    - main
  when: manual
  needs:
    - preview  # Changed from install to preview to maintain proper flow

destroy-dev:
  stage: dev
  script:
    - echo "Running Pulumi destroy for dev"
    - pulumi stack select dev || pulumi stack init dev
    - pulumi destroy --yes --non-interactive --color always
  only:
    - main
  when: manual
  dependencies:
    - deploy-to-dev
  needs:
    - deploy-to-dev