image:
  name: pulumi/pulumi:latest
  entrypoint: [""]

stages:
  - validate
  - install
  - preview
  - deploy

cache:
  paths:
    - .pulumi
    - node_modules/

variables:
  AWS_REGION: "us-east-2"
  PULUMI_BACKEND_URL: "s3://${PULUMI_S3_BUCKET}"

before_script:
  - echo "Setting up environment variables"
  - export AWS_REGION=$AWS_REGION
  - export PULUMI_CONFIG_PASSPHRASE=$PULUMI_CONFIG_PASSPHRASE
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export PULUMI_BACKEND_URL=$PULUMI_BACKEND_URL
  - pulumi login ${PULUMI_BACKEND_URL}

validate:
  stage: validate
  script:
    - echo "Validating project structure"
    - |
      if [ ! -f "package.json" ]; then
        echo "ERROR: package.json not found!"
        echo "Please run 'pulumi new' to initialize your project"
        exit 1
      fi
    - |
      if [ ! -f "Pulumi.yaml" ]; then
        echo "ERROR: Pulumi.yaml not found!"
        echo "Please run 'pulumi new' to initialize your project"
        exit 1
      fi
    - echo "Project structure validation passed"
  only:
    - branches

  
install:
  stage: install
  script:
    - echo "Installing dependencies"
    - npm ci --cache .npm --prefer-offline
    - echo "Installing dependencies completed"
  artifacts:
    paths:
      - .pulumi
      - node_modules/
    expire_in: 1h
  only:
    - branches
  when: always  # Always run this job

preview:
  stage: preview
  script:
    - echo "Running Pulumi preview"
    - pulumi stack select dev || pulumi stack init dev
    - pulumi preview --stack dev --diff --non-interactive --color always
  dependencies:
    - install
  only:
    - branches  # Run on branches only
  when: manual  # Manual trigger for preview

deploy-to-production:
  stage: deploy
  script:
    - echo "Running Pulumi up"
    - pulumi up --yes --non-interactive --color always
  only:
    - main  # Run on main branch only
  when: manual  # Manual trigger for deployment

deployment-production:
  stage: deploy
  script:
    - echo "Running Pulumi up for production"
    - pulumi destroy --yes --non-interactive --color always
  only:
    - main  # Run on main branch only
  when: manual  # Manual trigger for deployment to production