image:
  name: pulumi/pulumi-python:latest
  entrypoint: [""]

stages:
  - validate
  - install
  - preview
  - deploy

cache:
  paths:
    - .pulumi
    - __pycache__/

variables:
  AWS_REGION: "us-east-2"
  PULUMI_BACKEND_URL: "s3://${PULUMI_S3_BUCKET}"

before_script:
  - echo "Setting up environment variables"
  - export AWS_REGION=$AWS_REGION
  - export PULUMI_CONFIG_PASSPHRASE=$PULUMI_CONFIG_PASSPHRASE
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export PULUMI_BACKEND_URL=$PULUMI_BACKEND_URL
  - pulumi login ${PULUMI_BACKEND_URL}

validate:
  stage: validate
  script:
    - echo "Validating project structure"
    - |
      if [ ! -f "requirements.txt" ]; then
        echo "ERROR: requirements.txt not found!"
        exit 1
      fi
    - |
      if [ ! -f "Pulumi.yaml" ]; then
        echo "ERROR: Pulumi.yaml not found!"
        exit 1
      fi
    - echo "Project structure validation passed"
  only:
    - branches

install:
  stage: install
  script:
    - echo "Installing Python dependencies"
    - pip install -r requirements.txt
    - echo "Dependencies installed"
  artifacts:
    paths:
      - .pulumi
      - __pycache__/
    expire_in: 1h
  only:
    - branches
  when: always

preview:
  stage: preview
  script:
    - echo "Running Pulumi preview"
    - pulumi stack select dev || pulumi stack init dev
    - pulumi preview --stack dev --diff --non-interactive --color always
  dependencies:
    - install
  only:
    - branches
  when: manual

deploy-to-production:
  stage: deploy
  script:
    - echo "Running Pulumi up"
    - pulumi up --yes --non-interactive --color always
  only:
    - main
  when: manual

deployment-production:
  stage: deploy
  script:
    - echo "Running Pulumi destroy for production"
    - pulumi destroy --yes --non-interactive --color always
  only:
    - main
  when: manual